### PR TITLE
Fix RFC 3339 date handling

### PR DESCRIPTION
**Pull request by rcrichton**
Glossy was mixing a time offset with UTC dates when producing syslog messages. This change fixes this so that time offsets are used properly.

Original discussion around this can be found here: #33

### CODE REVIEW

**Comment by rcrichton** [comment]
@squeeks how does this look to you?

**Comment by myndzi** [comment]
I'd like to see this merged so I can stop depending on a git repo fork.

For some reason this branch seems to produce significantly greater variance in my test suite. The difference between the date extracted from the message and a new date object is consistently 100-200ms, where before I gave it a range of 0-10 ms. A brief test of just producing messages seems to go the other way, however: straight up calls to .produce were much faster with this branch. Not sure what it's all about and I haven't had to wrap my head around this code for months, just thought it was worth mentioning.

**Comment by myndzi** [comment]
Ahh. The obvious answer: timestamps produced this way do not include milliseconds.

**Comment by rcrichton** [comment]
@myndzi thanks for reminding me that this PR is still open.

@squeeks any chance we could get this merged in now?

**Comment by sebastianhaas** [comment]
@squeeks could you merge this?

**Pull request merged**
